server:
  port: 8095

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/authentication
    username: root
    password: 1234
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_schema: oauth_user
    generate-ddl: true
